######################
#  Gavin St. George  #
######################


###############
#  Site info  #
###############

# Site name
#   Appears in navbar and titlebar
title: Dealer Envy

# Locale
locale: en_US

# Site tagline
#   Appears in navbar and titlebar
tagline: On-the-lot services that drive your sales

# Author
#   Causes a footer to appear at the bottom of each page
author: Dealer Envy Inc

# Favicon
#   Path to file (png/ico) to use as site's favicon
favicon: /assets/images/logo-square.png

# Accent Color
#   Color used for navbar, footer, buttons, etc.
accent-color: "#005195"

# Background color
background-color: "#f0f0f0"

# Google Analytics Tag
gtag: G-PJ8QGKN9YZ


############
#  Navbar  #
############

# Site logo
#   Appears in the leftmost position of the navbar
#   It is recommended to use a square image
logo: /assets/images/logo-square.png

# Don't display the site title & tagline in the navbar
#navbar-hide-title: true

# Override the title shown in the navbar
#navbar-title:

# Override the tagline shown in the navbar
#navbar-tagline:

# Links to display in the navbar
navbar-links:
  Home: "/"
  Services:
    - Photos: "/services#photos"
    - Smart Overlays: "/services#overlays"
    - Equipped Option Tiles: "/services#tiles"
    - Billboards: "/services#billboards"
    - Background Replacement: "/services#backgrounding"
    - Videos: "/services#videos"
    - 360 Spins: "/services#360spins"
    - SiriusXM Radio Refresh: "/services#sxm"
    - Labels & Addendums: "/services#labels"
  Samples: "/samples"
  Careers: "/careers"
  Contact: "/contact"
  Portal: "https://admin.unitsinventory.com/index.php/reseller/dealer"

  # Link Label: "https://link.com/"
  # Section Label:
  #   - Link Label: "https://link.com/"
  #   - Link Label: "https://link.com/"  


#######################
#  Sitewide CSS & JS  #
#######################

css:
  - /assets/css/main.css
js:
  - /assets/js/main.js

sass: 
  sass_dir: /assets/css


#########################
#  Default YAML values  #
#########################

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


##############
#  Excludes  #
##############

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - CHANGELOG.md
  - CNAME
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - vendor/
