######################
#  Gavin St. George  #
######################


###############
#  Site info  #
###############

# Site name
#   Appears in navbar and titlebar
title: Dealer Solutions

# Locale
locale: en_US

# Site tagline
#   Appears in navbar and titlebar
tagline: On-the-lot services that drive your sales

# Author
#   Causes a footer to appear at the bottom of each page
author: Dealer Solutions Corp

# Favicon
#   Path to file (png/ico) to use as site's favicon
favicon: /assets/images/ds_logo_square.png

# Accent Color
#   Color used for navbar, footer, buttons, etc.
accent-color: "#004d99"

# Google Analytics Tag
gtag: G-R7H32259Z2


############
#  Navbar  #
############

# Site logo
#   Appears in the leftmost position of the navbar
#   It is recommended to use a square image
logo: /assets/images/ds_logo_square.png

# Don't display the site title & tagline in the navbar
navbar-hide-title: #true

# Override the title shown in the navbar
navbar-title:

# Override the tagline shown in the navbar
navbar-tagline:

# Links to display in the navbar
navbar-links:
  Home: "/"
  Services:
    - Photos: "/services#photos"
    - Dynamic Overlays: "/services#overlays"
    - Equipped Option Tiles: "/services#tiles"
    - Custom Images: "/services#custimgs"
    - Background Replacement: "/services#backgrounding"
    - Videos: "/services#videos"
    - 360 Spins: "/services#360spins"
    - SiriusXM Radio Refresh: "/services#sxm"
    - Labels & Addendums: "/services#labels"
  Samples: "/samples"
  Careers: "/careers"
  Contact: "/contact"
  Portal: "https://admin.unitsinventory.com/index.php/reseller/dealer"

  # Link Label: "https://Link.com/"
  # Section Label:
  #   - Link Label: "https://Link.com/"
  #   - Link Label: "https://Link.com/"  


#######################
#  Sitewide CSS & JS  #
#######################

css:
  - /assets/css/main.css
js:
  - /assets/js/main.js

sass: 
  sass_dir: /assets/css


#########################
#  Default YAML values  #
#########################

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


##############
#  Excludes  #
##############

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - CHANGELOG.md
  - CNAME
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - vendor/
