######################
#  Gavin St. George  #
######################


###############
#  Site info  #
###############

# Site name
#   Appears in navbar and titlebar
title: Dealer Solutions

# Locale
locale: en_US

# Site tagline
#   Appears in navbar and titlebar
tagline: On-the-lot services that drive your sales

# Author
#   Causes a footer to appear at the bottom of each page
author: Dealer Solutions Corp

# Favicon
#   Path to file (png/ico) to use as site's favicon
favicon: /assets/images/ds_logo_square.png

# Google Analytics Tag
gtag: G-R7H32259Z2


############
#  Navbar  #
############

# Site logo
#   Appears in the leftmost position of the navbar
#   It is recommended to use a square image
logo: /assets/images/ds_logo_square.png

# Show the site title & tagline in the navbar
#   If the site logo is set, this will appear to its right
navbar-show-title: true

# Links to display in the navbar
navbar-links:
  Home: "/"
  Services: "/services"
  Portal: "https://admin.unitsinventory.com/index.php/reseller/dealer"

  # Link Label: "https://Link.com/"
  # Section Label:
  #   - Link Label: "https://Link.com/"
  #   - Link Label: "https://Link.com/"  


#####################
#  Color Overrides  #
#####################

page-color: "#f3f3f3"         # Page background color
txt-color:                    # Text color
link-color:                   # Link color
accent-color: "#004d99"       # Background color used in navbar, footer, buttons, etc.
accent-txt-color: "#f3f3f3"   # Text color used in navbar, footer, buttons, etc.


#########################
#  Default YAML values  #
#########################

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


##############
#  Excludes  #
##############

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - CHANGELOG.md
  - CNAME
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - vendor/
